# Generated by Django 5.0.9 on 2025-10-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата створення'),
        ),
        migrations.AddIndex(
            model_name='postimage',
            index=models.Index(fields=['post', 'order'], name='blog_postim_post_id_a1bc87_idx'),
        ),
    ]
