# Generated by Django 5.0.9 on 2025-10-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
